config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts', to: 'posts#create', as: 'create_user_post'

  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:id/comments', to: 'comments#create', as: 'create_user_post_comment'

  get '/users/:user_id/posts/:id/likes/new', to: 'likes#new', as: 'new_user_post_like'
  post '/users/:user_id/posts/:id/likes', to: 'likes#create', as: 'create_user_post_like'

  resources :users, only: %i(index show) do
    resources :posts, only: %i(index show) do
      resources :comments, only: %i(new create)
      resources :likes, only: %i(new create)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  after_save :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  after_save :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  after_save :update_post_counter

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validate :validation_comments_counter
  validate :validation_likes_counter

  after_initialize :initialize_comments_counter
  after_initialize :initialize_likes_counter

  def update_post_counter
    author.update(post_counter: author.posts.count)
  end

  def most_recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def validation_comments_counter
    return unless comments_counter.present? && (!comments_counter.is_a?(Integer) || comments_counter.negative?)

    errors.add(:comments_counter, 'It must be a number greater than or equal to zero') unless comments_counter.zero?
  end

  def validation_likes_counter
    return unless likes_counter.present? && (!likes_counter.is_a?(Integer) || likes_counter.negative?)

    errors.add(:likes_counter, 'It must be a number greater than or equal to zero') unless likes_counter.zero?
  end

  def initialize_comments_counter
    self.comments_counter ||= 0
  end

  def initialize_likes_counter
    self.likes_counter ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validate :validation_posts_counter

  after_initialize :initialize_post_counter

  def most_recent_post(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  private

  def validation_posts_counter
    return unless post_counter.present? && (!post_counter.is_a?(Integer) || post_counter.negative?)

    errors.add(:post_counter, 'It must be a number greater than or equal to zero') unless post_counter.zero?
  end

  def initialize_post_counter
    self.post_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.first
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:id])
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def create
    @post = Post.find(params[:id])
    @like = @post.likes.new
    @like.author = current_user

    if @like.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))
    @post.author = current_user
    if @post.save
      redirect_to user_posts_path
    else
      render :new, locals: { post: @post }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = Post.where(author_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_with(model: [@post, @comment], url: user_post_comments_path(@post.author, @post), local: true) do |form| %>
  <div class="field">
    <%= form.text_area :text, placeholder: 'Leave a comment'%>
  </div>
  <div class="actions">
    <%= form.submit 'Create Comment' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'style', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= form_with(model: [@post, @like], url: user_post_likes_path(@post.author, @post, @like), local: true) do |form| %>
  <div class="actions">
    <%= form.submit 'Like the post' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class='user_div'>
  <div class='user_photo'>
    <%= image_tag @user.photo %>
  </div>
  <div class='user_info'>
    <p class='user_name'><%= @user.name %> <br>
    <%= link_to new_user_post_path(@user), class: 'btn' do %>
    <button class='btn'>Create new post</button>
  <% end %>    <p class='number_of_posts'>Number of posts: <%= @user.post_counter %></p>
  </div>
</div>

<div class='posts'>
  <% @posts.each do |post| %>
    <div class='individual_post'>
      <%= link_to user_post_path(@user, post) do %>
        <h3><%= post.title %></h3>
        <p>
          <%= truncate(post.text, length: 130, omission: '...') %>
          <% if post.text.length > 20 %>
          <% end %>
        </p>
        <div class='comments'>
          <p class='number_of_comments'>Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
        </div>
        <div class='comments_div'>
          <h3>Comments:</h3>
          <% post.most_recent_comments.each do |comment| %>
            <p><%= comment.author.name %>: <%= comment.text %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class= 'main_form_div'>
  <h1>New Post</h1>
<%= form_with model: [:user, @post], data: { turbo: false }, local: true do |form| %>
   <div class="field">
    <%= form.text_field :title, placeholder: 'Title'%>
  </div>
  <div class="field">
    <%= form.text_area :text, placeholder: 'Your post' %>
  </div>
  <div class="actions">
    <%= form.submit 'Create Post' %>
  </div>
<% end %>
</div>

app/views/posts/show.html.erb
<div class='posts_page'>
  <div class='individual_large_post'>
    <h3><%= @post.title %></h3>
    <p class='number_of_posts'> Comments: <%= @post.comments_counter %> Likes: <%= @post.likes_counter %></p>
    <p class='whole_post'><%= @post.text %></p>
    
    <%= link_to new_user_post_comment_path(@post), class: 'btn' do %>
      <button class='btn'>Add a comment</button>
    <% end %>
    
    <%= link_to new_user_post_like_path(@post.author), class: "btn" do %>
      <button class='btn'>Add a like</button>
    <% end %>

  </div>

  <h3>Comments:</h3>
  <% @post.comments.each do |comment| %>
    <div class='comments_div'>
      <p><%= comment.text %></p>
      <p>Written by: <%= comment.author.name %></p>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class='main_div'>
  <% @users.each do |user| %>
    <div class='user_div'>
      <%= link_to user_path(user) do %>
        <div class='user_photo'>
          <%= image_tag user.photo %>
        </div>
        <div class='user_info'>
          <p class='user_name'><%= user.name %></p>
          <p class='number_of_posts'>Number of posts: <%= user.post_counter %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='user_div'>
  <div class='user_photo'>
    <%= image_tag @user.photo %>
  </div>
  <div class='user_info'>
    <p class='user_name'><%= @user.name %></p>
    <p class='number_of_posts'>Number of posts: <%= @user.post_counter %></p>
  </div>
</div>

<div class='user_bio'>
  <%= @user.bio %>
</div>

<div class='posts'>
  <% post_number = 1 %>
  <% @user.most_recent_post.each do |post| %>
    <div class='individual_post'>
      <h2>Post #<%= post_number %></h2>
      <h3><%= post.title %></h3>
      <p>
        <%= truncate(post.text, length: 130, omission: '...') %>
        <% if post.text.length > 20 %>
        <% end %>
      </p>
      <div class='comments'>
        <p class='number_of_comments'>Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
      </div>
    </div>
    <% post_number += 1 %>
  <% end %>
</div>

<%= link_to user_posts_path(@user), class: 'button' do %>
  <button class='button'>See All Posts</button>
<% end %>